title: "the triangle sky"
author: "nick daniels"
description: "drawings by nick daniels"
permalink: /:title/
lang: "en"

show_footer: true           # show the "previous" and "next" links at the end of each post
dark_theme: false            # use the dark mode as default
dark_header: true            # keep the header dark
dark_footer: true           # keep the footer dark
# style: minimal             # use a simpler style inspired by the minima theme

navigation:                  # site navigation in the header
  - about.md
  - twitter: "https://twitter.com/nickdaniels"

#icons:                      # icons in the header, see http://fontawesome.com/icons
#  envelope: "mailto:niklasbuschmann@users.noreply.github.com"
#  github: "https://github.com/niklasbuschmann/contrast"
#  rss: "/contrast/feed.xml"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins:
 - jekyll-feed
 - jekyll-default-layout
